# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpTable',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('odd', models.BooleanField(default=True)),
                ('date', models.CharField(max_length=120)),
                ('corpus', models.CharField(max_length=250)),
                ('more', models.CharField(max_length=120)),
            ],
        ),
    ]
