# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exptable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exptable',
            name='corpus',
            field=models.TextField(),
        ),
    ]
