# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_formationtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationtable',
            name='more',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
