# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsDocs',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('doc_icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='docs',
        ),
        migrations.AddField(
            model_name='projectsdocs',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='main.Projects'),
        ),
    ]
