# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161110_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsdocs',
            name='link',
            field=models.CharField(default='wip', max_length=200),
            preserve_default=False,
        ),
    ]
