# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_projectsdocs_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='projectsdocs',
            name='project',
        ),
        migrations.AddField(
            model_name='projects',
            name='docs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectsDocs', to='main.ProjectsDocs'),
        ),
    ]
