# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20161110_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='docs',
        ),
        migrations.AddField(
            model_name='projectsdocs',
            name='project_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='main.Projects'),
        ),
    ]
