# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20161110_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterItems',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='projectsdocs',
            name='project_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs_set', to='main.Projects'),
        ),
    ]
