# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('uid', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('img', models.CharField(max_length=120)),
                ('link', models.CharField(max_length=120)),
            ],
        ),
    ]
