# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devblog', '0002_navbar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navbar',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('CV', 'CV'), ('Site', 'Site'), ('Serveur', 'Serveur'), ('Linux', 'Linux'), ('Divers', 'Divers')], max_length=100),
        ),
    ]
